### ISSUE TITLE
[AntiProxy] You are blacklisted from this server のメッセージを日本語化したうえで適切に修正する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/seichi_infra#2528]
永久BANだと勘違いされてお問い合わせされることが多い

**Comment by Lucky3028** [comment]
本番のロビーで動いている内容がこれになります。

```yaml
Options:
  UseLightweight: true
  useSSL: true
  APIKey: "k0e51f-999948-i22341-321b23"
  APITimeout: 5000
  Strictness: 1
  PunishmentType: "Kick"
  AutoBlacklist: true

Messages:
  Prefix: "&9&l[AntiProxy]"
  PunishmentMessage: "You are not allowed to join this server with Proxies."
  BlackListPunishMessage: "You are blacklisted from joining this server."
  NoPermission: "You do not have permission for this command!"
  ReloadMessage: "Config Reloaded Successfully."
  BlackListAddedMessage: "Added IP Successfully to BlackList."
  WhiteListAddedMessage: "Added IP Successfully to WhiteList."
  BlackListRemovedMessage: "Removed IP Successfully from BlackList."
  WhiteListRemovedMessage: "Removed IP Successfully from WhiteList."
  IPNotInList: "IP does not exist in current List."
  IPExistsInList: "IP already exists in current List."
  NotifyAdminMessage: "Player {Player} tried to login with a potential proxy with IP: {IP}"
  GetBlackListColor: "&9"
  GetWhiteListColor: "&9"
  WhiteListHeader: "&9AntiProxy WhiteListed IPs"
  BlackListHeader: "&9AntiProxy BlackListed IPs"

Permissions:
  Reload: "AntiProxy.Reload"
  WhiteList: "AntiProxy.WhiteList"
  BlackList: "AntiProxy.BlackList"
  NotifyAdmin: "AntiProxy.Notify"
  GetBlackListPermission: "AntiProxy.GetBlackList"
  GetWhiteListPermission: "AntiProxy.GetWhiteList"
  Help: "AntiProxy.help"
```

**Comment by Lucky3028** [comment]
本番のロビーで今これが動いています。`APIKey`だけ編集してあります。

```yaml
Options:
  UseLightweight: true
  useSSL: true
  APIKey: "***redacted***"
  APITimeout: 5000
  Strictness: 1
  PunishmentType: "Kick"
  AutoBlacklist: true

Messages:
  Prefix: "&9&l[AntiProxy]"
  PunishmentMessage: "You are not allowed to join this server with Proxies."
  BlackListPunishMessage: "You are blacklisted from joining this server."
  NoPermission: "You do not have permission for this command!"
  ReloadMessage: "Config Reloaded Successfully."
  BlackListAddedMessage: "Added IP Successfully to BlackList."
  WhiteListAddedMessage: "Added IP Successfully to WhiteList."
  BlackListRemovedMessage: "Removed IP Successfully from BlackList."
  WhiteListRemovedMessage: "Removed IP Successfully from WhiteList."
  IPNotInList: "IP does not exist in current List."
  IPExistsInList: "IP already exists in current List."
  NotifyAdminMessage: "Player {Player} tried to login with a potential proxy with IP: {IP}"
  GetBlackListColor: "&9"
  GetWhiteListColor: "&9"
  WhiteListHeader: "&9AntiProxy WhiteListed IPs"
  BlackListHeader: "&9AntiProxy BlackListed IPs"

Permissions:
  Reload: "AntiProxy.Reload"
  WhiteList: "AntiProxy.WhiteList"
  BlackList: "AntiProxy.BlackList"
  NotifyAdmin: "AntiProxy.Notify"
  GetBlackListPermission: "AntiProxy.GetBlackList"
  GetWhiteListPermission: "AntiProxy.GetWhiteList"
  Help: "AntiProxy.help"
```
